reconnect = true
[events]
"listening" = "blsd -t 0.06 -b 6 red"
"silence" = "blsd -t 0.06 -b 6 red"
"processing" = "blsd -t 0.06 -b 6 red"
"ready" = "blsd -t 0.06 -b 6 red"
"paused" = "blsd hide"
"warming_up" = "blsd -t 0.06 -b 6 yellow"
